name: Deployment - Reusable workflow

on: 
    workflow_call: 
       inputs:
         mongodb_uri:
          required: true
          type: string
         kubectl-version:
          description: Provide the required kubectl version
          default: v1.26.0
          required: false
          type: string
         k8s-manifest-dir:
          description: Directory containing Kubernetes Manifests files
          default: kubernetes/
          required: true
          type: string
         environment:
          description: Provide the deployment Environment
          default: dev
          required: true
          type: string     
       secrets:
          k8s-kubeconfig:
            required: true
          mongodb-password:
            required: true
       outputs:
        application-uri:
          value: ${{ jobs.reuse-deploy.outputs.APP_INGRESS_URL }}     


jobs:
    reuse-deploy:
        environment: 
            name: ${{ inputs.environment }}
            url: https://${{ steps.set-ingress-host-address.outputs.APP_INGRESS_HOST}}
        outputs:
            APP_INGRESS_URL: ${{ steps.set-ingress-host-address.outputs.APP_INGRESS_HOST}}
        runs-on: ubuntu-latest
        steps:
          - name: Checkout Repo
            uses: actions/checkout@v4

          - name: Install Kubectl Cli
            uses: azure/setup-kubectl@v4
            with:
              version: '${{ inputs.kubectl-version }}'

          - name: Set Kubernet Context
            uses: azure/k8s-set-context@v4
            with:
             method: kubeconfig
             kubeconfig: ${{ secrets.k8s-kubeconfig}}

          - name: Fetch Kubernetes Cluster Details
            run: |
              kubectl version 
              echo ---------------------------
              kubectl get nodes 
            
          - name: Save Nginx Ingress Controller IP as a GITHUB Environment Variable
            run: |
             echo "INGRESS_IP=$(kubectl -n ingress-nginx get svc ingress-nginx-controller -o jsonpath="{.status.loadBalancer.ingress[0].ip}")" >> $GITHUB_ENV    

          - name: Replace Tokens In Manifest Files
            uses: cschleiden/replace-tokens@v1
            with:
              tokenPrefix: '_{_'
              tokenSuffix: '_}_'
              files: '["${{ inputs.k8s-manifest-dir }}*.yaml"]'
            env:
              NAMESPACE: ${{ vars.NAMESPACE}}
              REPLICAS: ${{ vars.REPLICAS}}
              IMAGE: ${{ vars.DOCKERHUB_USERNAME }}/solar-system:${{ github.sha }}
              INGRESS_IP: ${{ env.INGRESS_IP }}
        
          - name: Check Files
            run: |
             cat ${{ inputs.k8s-manifest-dir }}/*.yaml 

          - name: Create MongoDB Secret
            run: |
              kubectl -n ${{ vars.NAMESPACE }} create secret generic mongo-db-creds \
              --from-literal=MONGO_URI=${{ inputs.mongodb_uri }} \
              --from-literal=MONGO_USERNAME=${{ vars.MONGO_USERNAME }} \
              --from-literal=MONGO_PASSWORD=${{ secrets.mongodb-password }} \
              --save-config \
              --dry-run=client \
              -o yaml | kubectl apply -f -

          - name: Deploy To Development Env
            run: |
             kubectl apply -f ${{ inputs.k8s-manifest-dir }} 
            
          - name: Set App Ingress Host URL
            id: set-ingress-host-address
            run: |
             echo "APP_INGRESS_HOST=$(kubectl get ingress -n ${{ vars.NAMESPACE }} -o jsonpath="{.items[0].spec.tls[0].hosts[0]}")" >> "$GITHUB_OUTPUT"        